django_crud_example/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainsite.urls')),
]

mainsite/urls.py
from django.urls import path
from .views import LinkmanListView, LinkmanDetailView, LinkmanCreateView, LinkmanUpdateView, LinkmanDeleteView

urlpatterns = [
    # 列表
    path('', LinkmanListView.as_view(), name='list'),
    # 詳細
    path('detail/<int:pk>/', LinkmanDetailView.as_view(), name='detail'),
    # 建立
    path('create/', LinkmanCreateView.as_view(), name='create'),
    # 更新
    path('update/<int:pk>/', LinkmanUpdateView.as_view(), name='update'),
    # 刪除
    path('delete/<int:pk>/', LinkmanDeleteView.as_view(), name='delete'),
]

mainsite/models.py
from django.db import models
from django.core import validators

# Create your models here.
class Linkman(models.Model):
    SEX_CHOICES = (
        (1, '男'),
        (2, '女'),
    )

    name = models.CharField(
        verbose_name='姓名',
        max_length=15
    )

    sex = models.IntegerField(
        verbose_name='性別',
        choices=SEX_CHOICES,
        default=1
    )

    tel = models.CharField(
        verbose_name='電話',
        max_length=15
    )

    email = models.EmailField(
        verbose_name='電子郵件',
        validators=[validators.EmailValidator]
    )

    created_at = models.DateTimeField(
        verbose_name='建立日',
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        verbose_name='更新日',
        auto_now=True
    )

mainsite/forms.py
from django import forms
from .models import Linkman

class LinkmanForm(forms.ModelForm):
    class Meta:
        model = Linkman
        fields = ('name', 'sex', 'tel', 'email')
        widgets = {
            'name': forms.TextInput(),
            'sex': forms.RadioSelect(),
            'tel': forms.TextInput(),
            'email': forms.EmailInput(),
        }

mainsite/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Linkman
from .forms import LinkmanForm

# Create your views here.

# 列表
class LinkmanListView(LoginRequiredMixin, ListView):
    model = Linkman
    template_name = 'mainsite/linkman_list.html'

# 詳細
class LinkmanDetailView(LoginRequiredMixin, DetailView):
    model = Linkman
    template_name = 'mainsite/linkman_detail.html'

# 建立
class LinkmanCreateView(LoginRequiredMixin, CreateView):
    model = Linkman
    form_class = LinkmanForm
    template_name = 'mainsite/linkman_form.html'
    success_url = reverse_lazy('list')

# 更新
class LinkmanUpdateView(LoginRequiredMixin, UpdateView):
    model = Linkman
    form_class = LinkmanForm
    template_name = 'mainsite/linkman_form.html'
    success_url = reverse_lazy('list')

# 刪除
class LinkmanDeleteView(LoginRequiredMixin, DeleteView):
    model = Linkman
    template_name = 'mainsite/linkman_detail.html'
    success_url = reverse_lazy('list')

mainsite/templates/mainsite/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <meta charset="UTF-8">
    <title>通訊錄</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">通訊錄</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:logout'%}">登出</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

mainsite/templates/mainsite/linkman_detail.html
{% extends "./base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="float-left">
                <h3>
                    {% if 'delete' in request.path %}
                        刪除
                    {% else %}
                        詳細
                    {% endif %}
                </h3>
            </div>
            <div class="float-right">
                {% url 'list' as list %}
                {% bootstrap_button '回列表' button_type='link' href=list button_class='btn-primary' %}
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-3">
                <p>姓名</p>
            </div>
            <div class="col-9">
                <p>{{ linkman.name }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <p>性別</p>
            </div>
            <div class="col-9">
                <p>{{ linkman.get_sex_display }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <p>電話</p>
            </div>
            <div class="col-9">
                <p>{{ linkman.tel }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <p>電子郵件</p>
            </div>
            <div class="col-9">
                <p>{{ linkman.email }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <p>建立日</p>
            </div>
            <div class="col-9">
                <p>{{ linkman.created_at|date:'Y/m/d G:i:s' }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <p>更新日</p>
            </div>
            <div class="col-9">
                <p>{{ linkman.updated_at|date:'Y/m/d G:i:s' }}</p>
            </div>
        </div>
        {% if 'delete' in request.path %}
            <form method="post" id="myform">
                {% csrf_token %}
                {% bootstrap_button '刪除' button_type='submit' button_class='btn-danger' %}
            </form>
        {% endif %}
    </div>
</div>

{% endblock %}

mainsite/templates/mainsite/linkman_form.html
{% extends "./base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="float-left">
                <h3>
                    {% if linkman %}
                        更新
                    {% else %}
                        建立
                    {% endif %}
                </h3>
            </div>
            <div class="col-12">
                <div class="float-right">
                    {% url 'list' as list %}
                    {% bootstrap_button '回列表' button_type='link' href=list button_class='btn-primary' %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post" id="myform">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button '送出' button_type='submit' button_class='btn-primary' %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

mainsite/templates/mainsite/linkman_list.html
{% extends 'mainsite/base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="float-left">
                <h3>列表</h3>
            </div>
            <div class="float-right">
                {% url 'create' as create %}
                {% bootstrap_button '建立' button_type='link' href=create button_class='btn-primary' %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                {% for linkman in linkman_list %}
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-3">
                            <p>姓名</p>
                        </div>
                        <div class="col-9">
                            <p>{{ linkman.name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>建立日</p>
                        </div>
                        <div class="col-9">
                            <p>{{linkman.created_at|date:"Y/m/d G:i:s"}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="float-right">
                                {% url 'detail' linkman.pk as detail %}
                                {% url 'update' linkman.pk as update %}
                                {% url 'delete' linkman.pk as delete %}
                                {% bootstrap_button '詳細' button_type='link' href=detail button_class='btn-primary' %}
                                {% bootstrap_button '更新' button_type='link' href=update button_class='btn-primary' %}
                                {% bootstrap_button '刪除' button_type='link' href=delete button_class='btn-primary' %}
                            </div>
                        </div>
                    </div>
                </li>
                {% empty %}
                <li class="list-group-item">
                    無資料
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}